# Rule_ID:31
# @title [Catalog] dct:modified is a recommended property for Catalog
# @tag catalog
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Catalog.
  FILTER(!(EXISTS { ?s dct:modified ?desc})).
  BIND (rdf:type AS ?p).
  BIND (dcat:Catalog AS ?o).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (31 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dct:modified is a recommended property for Catalog." AS ?Rule_Description).
  BIND (concat("The dcat:Catalog ",str(?o)," does not have a dct:modified property." AS ?Message).
}