# Rule_ID:1
# @title [Agent] foaf:name should be a literal
# @tag agent
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a foaf:Agent.
  ?s foaf:name ?o.
  FILTER(!isLiteral(?o)).
  BIND (foaf:name AS ?p)
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (1 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("The foaf:name property should be a literal." AS ?Rule_Description).
  BIND (concat("The foaf:name property ",str(?p)," is not a literal") AS ?Message).
}
