# Rule_ID:46
# @title [Dataset] dcat:distribution should be a Distribution
# @tag dataset
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Dataset.
  ?s dcat:distribution ?o
  ?o ?pred ?val.
  FILTER(!EXISTS {?o a dcat:Distribution}).
  BIND (dcat:distribution AS ?p).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (46 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:distribution should be a Distribution." AS ?Rule_Description).
  BIND (concat("The dcat:distribution ",str(?o)," is not a distribution.") AS ?Message).
}