# Rule_ID:61
# @title [Dataset] dcat:landingPage should be a resource
# @tag dataset

PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Dataset.
  ?s dcat:landingPage ?o.
  FILTER(!isURI(?o)).
  BIND (dcat:landingPage AS ?p).
  BIND ("Dataset" AS ?Class_Name).
  BIND (61 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:landingPage should be a resource." AS ?Rule_Description).
  BIND (concat("The dcat:landingPage ",str(?p)," is not a resource.") AS ?Message).
}
