# Rule_ID:54
# @title [Dataset] dcat:theme should be a resource
# @tag dataset

PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o 
WHERE {
  ?s a dcat:Dataset.
  ?s dcat:theme ?o.
  FILTER(!isURI(?o)).
  BIND (dcat:theme AS ?p).
  BIND ("Dataset" AS ?Class_Name).
  BIND (54 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:theme should be a resource." AS ?Rule_Description).
  BIND (concat("The dcat:theme ",str(?o)," is not a resource.") AS ?Message).
}
