# Rule_ID:28
# @title [Catalog] dcat:themeTaxonomy should be a resource
# @tag catalog
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Catalog.
  ?s dcat:themeTaxonomy ?o.
  FILTER(!isIRI(?o)).
  BIND (dcat:themeTaxonomy AS ?p).
  BIND ("Catalog" AS ?Class_Name).
  BIND (28 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:themeTaxonomy should be a resource." AS ?Rule_Description).
  BIND (concat("The dcat:themeTaxonomy ",str(?o)," is not a resource.") AS ?Message).
}
