# Rule_ID:17
# @title [Catalog] foaf:homepage should be a foaf:Document
# @tag catalog
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Catalog.
  ?s foaf:homepage ?o.
  FILTER(!EXISTS {?o a foaf:Document}).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (17 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("foaf:homepage should be a foaf:Document." AS ?Rule_Description).
  BIND (concat("The foaf:homepage ",str(?o)," is not a foaf:Document.") AS ?Message).
}
