# Rule_ID:41
# @title [Dataset] adms:contactPoint is a recommended property for Dataset
# @tag dataset
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Dataset.
  FILTER(!(EXISTS { ?s adms:contactPoint ?cPoint})).
  BIND (rdf:type AS ?p).
  BIND (dcat:Dataset AS ?o).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (41 AS ?Rule_ID).
  BIND ("warning" AS ?Rule_Severity).
  BIND ("adms:contactPoint is a recommended property for Dataset." AS ?Rule_Description).
  BIND (concat("The dcat:Dataset ",str(?s)," does not have the adms:contactPoint property.") AS ?Message).
}