# Rule_ID:80
# @title [Distribution] dcat:accessURL should be a resource
# @tag distribution
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o 
WHERE {
  ?s a dcat:Distribution.
  ?s dcat:accessURL ?o.
  FILTER(!isURI(?o)).
  BIND (dcat:accessURL AS ?p).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (80 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:accessURL should be a resource." AS ?Rule_Description).
  BIND (concat("The dcat:accessURL ",str(?s)," is not a resource.") AS ?Message).
}
