# Rule_ID:5
# @title [Catalog] dcat:dataset should be a Dataset
# @tag catalog
# @endpoint http://localhost:3030/dcat-ap_validator/query

PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?Rule_Origin ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
WHERE {
  ?s a dcat:Catalog.
  ?s dcat:dataset ?o.
  FILTER(!EXISTS {?o a dcat:Dataset}).
  BIND ("DCAT-AP" AS ?Rule_Origin).
  BIND (5 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("dcat:dataset should be a Dataset." AS ?Rule_Description).
  BIND (concat("The dcat:Dataset ",str(?o)," does not exist.") AS ?Message).
}
